packages:
  - packages/*
  - examples/*
  - __tests__

engineStrict: true
strictPeerDependencies: true
shellEmulator: true
preferWorkspacePackages: true
linkWorkspacePackages: true
enablePrePostScripts: true

minimumReleaseAge: 1440

catalog:
  "@types/node": ^25.9.3
  "@types/react": ^19.2.17
  glob: ^13.0.6
  react: ^19.2.7
  tsdown: ^0.22.2
  vite: ^7.2.2
  vitest: ^4.1.8
  wasm-pack: ^0.15.0
  wrangler: ^4.100.0

allowBuilds:
  "@biomejs/biome": true
  "@parcel/watcher": true
  esbuild: true
  sharp: true
  wasm-pack: true
  workerd: true
