{
  "packages": ["packages/*", "examples/*", "__tests__", "__tests__/*"],
  "onlyBuiltDependencies":
    ["@biomejs/biome", "esbuild", "sharp", "wasm-pack", "workerd"],
  "catalog":
    {
      "@types/node": "^24.10.1",
      "@types/react": "^19.2.3",
      "glob": "^11.0.3",
      "react": "^19.2.0",
      "tsup": "^8.5.0",
      "vite": "^7.2.2",
      "vitest": "^4.0.8",
      "wasm-pack": "^0.13.1",
      "wrangler": "^4.47.0",
    },
}
