name: "\U0001F680 Feature Request"
description: Create a feature request
title: "\U0001F680 Feature Request:"
labels: ["enhancement"]
assignees:
  - kumardeo

body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to file a feature request! Please fill out this form as completely as possible.
  - type: dropdown
    id: project
    attributes:
      multiple: false
      label: Which project is this feature request for?
      options:
        - "@cf-wasm/photon"
        - "@cf-wasm/png"
        - "@cf-wasm/quickjs"
        - "@cf-wasm/resvg"
        - "@cf-wasm/satori"
        - "@cf-wasm/og"
  - type: textarea
    attributes:
      label: Describe the feature you'd like to request
      description: A clear and concise description of what you want and what your use case is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
