name: Build and test

on: [workflow_call]

# env:
#   TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
#   TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
#   TURBO_REMOTE_ONLY: true

jobs:
  build_typecheck_test:
    name: 🔎 Typecheck and test
    uses: ./.github/workflows/build-reusable.yml
    with:
      afterBuild: npm run test # pnpm typecheck && pnpm test
    secrets: inherit
